/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;

import components.interfaces.IPanelInput;
import domain.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
/**
 *
 * @author siux
 */
public class FrmPersonv4 extends javax.swing.JFrame {

    /**
     * Creates new form FrmPersonv4
     */
    public FrmPersonv4() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInputPersonv31 = new components.PanelInputPersonv3();
        pnlConfig = new javax.swing.JPanel();
        cboxConfig = new javax.swing.JComboBox<>();
        lblConfig = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        pnlView = new javax.swing.JPanel();
        pnliPersonF2 = new components.PanelInputPerson();
        pnliPersonF1 = new components.PanelInputPersonv2();
        panelInputPersonv32 = new components.PanelInputPersonv3();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboxConfig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxConfig.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxConfigItemStateChanged(evt);
            }
        });

        lblConfig.setText("Konfiguracija:");

        javax.swing.GroupLayout pnlConfigLayout = new javax.swing.GroupLayout(pnlConfig);
        pnlConfig.setLayout(pnlConfigLayout);
        pnlConfigLayout.setHorizontalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(cboxConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        pnlConfigLayout.setVerticalGroup(
            pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConfigLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblConfig)
                    .addComponent(cboxConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlConfig, java.awt.BorderLayout.PAGE_START);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pnlView.setLayout(new java.awt.CardLayout());
        pnlView.add(pnliPersonF2, "F-2");
        pnlView.add(pnliPersonF1, "F-1");
        pnlView.add(panelInputPersonv32, "F-3");

        getContentPane().add(pnlView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxConfigItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxConfigItemStateChanged
       pnlView.setVisible(true);
       btnSubmit.setEnabled(true);
       CardLayout layout = (CardLayout)pnlView.getLayout();
       layout.show(pnlView, (String)evt.getItem());
    }//GEN-LAST:event_cboxConfigItemStateChanged

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        CardLayout layout = (CardLayout)pnlView.getLayout();
        String selected = (String)cboxConfig.getSelectedItem();
        IPanelInput currentInputPanelPerson = null;
        for (Component comp : pnlView.getComponents()) {
            if(comp.isVisible()){
                currentInputPanelPerson = (IPanelInput) comp;
            }
        }
        if(currentInputPanelPerson == null){
            throw new RuntimeException("Problem with panels. Null pointer.");
        }
        
        JOptionPane.showMessageDialog(this, ((Person)currentInputPanelPerson.getValue()).toString(), "Saved", JOptionPane.INFORMATION_MESSAGE);
        //layout.next(pnlView);
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonv4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonv4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cboxConfig;
    private javax.swing.JLabel lblConfig;
    private components.PanelInputPersonv3 panelInputPersonv31;
    private components.PanelInputPersonv3 panelInputPersonv32;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlConfig;
    private javax.swing.JPanel pnlView;
    private components.PanelInputPersonv2 pnliPersonF1;
    private components.PanelInputPerson pnliPersonF2;
    // End of variables declaration//GEN-END:variables

    private void prepareView() {
        cboxConfig.removeAllItems();
        
        
       
        
        cboxConfig.addItem("F-1");
        cboxConfig.addItem("F-2");
        cboxConfig.addItem("F-3");
        
        cboxConfig.setSelectedItem(null);
        
        pnlView.setVisible(false);
        btnSubmit.setEnabled(false);
        
        
        
    }
}
