/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.forms;


import components.PanelInputThreeComboBox;
import components.PanelInputThreeRadioButton;
import components.PanelInputTxtField;
import components.interfaces.IPanelInput;
import domain.Gender;
import domain.Person;
import java.lang.reflect.Array;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import sun.misc.Perf;

/**
 *
 * @author siux
 */
public class FrmPerson extends javax.swing.JFrame {

    /**
     * Creates new form FrmPerson
     */
    public FrmPerson() {
        initComponents();
        prepareView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        pnliFirstName = new components.PanelInputTxtField();
        pnliLastName = new components.PanelInputTxtField();
        pnliGender = new components.PanelInputComboBox();
        pnliBirthday = new components.PanelInputTxtField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, java.awt.BorderLayout.CENTER);
        getContentPane().add(pnliFirstName, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pnliLastName, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(pnliGender, java.awt.BorderLayout.LINE_END);
        getContentPane().add(pnliBirthday, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        
        Person person = new Person();
        
        person.setFirstName((String)pnliFirstName.getValue());
        person.setLastName((String)pnliLastName.getValue());
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        
        try {
            person.setBirthday((Date)sdf.parse((String)pnliBirthday.getValue()));
        } catch (ParseException ex) {
            Logger.getLogger(FrmPerson.class.getName()).log(Level.SEVERE, null, ex);
            pnliGender.getLblInputFieldError().setText(ex.getMessage());
        }
        person.setGender(Gender.valueOf((String)pnliGender.getValue()));
        
        
        JOptionPane.showMessageDialog(this, person.toString(), "Saved", JOptionPane.INFORMATION_MESSAGE);
        
        /**
         *  System.out.println("First name: " + pnliFirstName.getValue());
            System.out.println("Last name: " + pnliLastName.getValue());
            System.out.println("Gender: " + pnliGender.getValue());
            System.out.println("Birthday: " + pnliBirthday.getValue());
         */
       
    }//GEN-LAST:event_btnSaveActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private components.PanelInputTxtField pnliBirthday;
    private components.PanelInputTxtField pnliFirstName;
    private components.PanelInputComboBox pnliGender;
    private components.PanelInputTxtField pnliLastName;
    // End of variables declaration//GEN-END:variables

    private String[] makeYearStringArray(){
        String[] years = new String[200];
        
        for(int i = 1900; i < 2100; i++){
            years[i - 1900] = "" + i;
        }
        
        return years;
    }

    private void prepareView() {
        //fixed
        pnliFirstName.getLblInputField().setText("First name:");
        pnliFirstName.getLblInputFieldError().setText("");
        
        // fixed( because we assume that user data is not located in some storage and only solution is to input some text)
        
        //fixed
        pnliLastName.getLblInputField().setText("Last name:");
        pnliLastName.getLblInputFieldError().setText("");
        
        // fixed( because we assume that user data is not located in some storage and only solution is to input some text)
        
        //fixed
        pnliGender.getLblInputField().setText("Gender:");
        pnliGender.getLblInputFieldError().setText("");
        
        //varies so we must encapsulate it
       // pnliGender.setInputFields((Object)new String[]{"Male", "Female", "Uruk-hai"});
        
        //fixed
        pnliBirthday.getLblInputField().setText("Birthday:");
        pnliBirthday.getLblInputFieldError().setText("");
        
        
        List<String> genders = new ArrayList<String>();
        genders.add("MALE");
        genders.add("FEMALE");
        genders.add("URUK_HAI");
        
        pnliGender.initialize(genders);
        
        /**
         * pnliBirthday.setInputFields((Object)new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14",
                                                            "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26",
                                                            "27", "28", "29", "30", "31"},
                                     (Object)new String[]{"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"},
                                     (Object)makeYearStringArray());
         */
        //varies so we must encapsulate it
    }

    

   
}
